package com.jesper.model;

import java.util.Date;

import lombok.Data;
@Data
public class Flow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.id
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Long id;

    private String tradecode;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.ftype
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Byte ftype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.qtimes
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Integer qtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.qprice
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Integer qprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.quanid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Long quanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.memberid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Long memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.shopid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Long shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.created
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Date created;

    
}