package com.jesper.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.Data;
@Data
public class Flow extends BaseObject{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.id
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Long id;

    private String tradecode;
    private Byte ftype;
    private Integer qtimes;
    private Integer qprice;
    private Long quanid;
    private Long memberid;
    private Long shopid;
    
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date created;
    
    private String shopName;
    private String mname;

    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date minSendtime;
    
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date maxSendtime;  
}