package com.jesper.model;

import java.util.Date;

public class Flow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.id
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.ftype
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Byte ftype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.qtimes
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Integer qtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.qprice
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Integer qprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.quanid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Long quanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.memberid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Long memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.shopid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Long shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.created
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.id
     *
     * @return the value of tb_flow.id
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.id
     *
     * @param id the value for tb_flow.id
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.ftype
     *
     * @return the value of tb_flow.ftype
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Byte getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.ftype
     *
     * @param ftype the value for tb_flow.ftype
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setFtype(Byte ftype) {
        this.ftype = ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.qtimes
     *
     * @return the value of tb_flow.qtimes
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Integer getQtimes() {
        return qtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.qtimes
     *
     * @param qtimes the value for tb_flow.qtimes
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setQtimes(Integer qtimes) {
        this.qtimes = qtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.qprice
     *
     * @return the value of tb_flow.qprice
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Integer getQprice() {
        return qprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.qprice
     *
     * @param qprice the value for tb_flow.qprice
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setQprice(Integer qprice) {
        this.qprice = qprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.quanid
     *
     * @return the value of tb_flow.quanid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Long getQuanid() {
        return quanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.quanid
     *
     * @param quanid the value for tb_flow.quanid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setQuanid(Long quanid) {
        this.quanid = quanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.memberid
     *
     * @return the value of tb_flow.memberid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Long getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.memberid
     *
     * @param memberid the value for tb_flow.memberid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setMemberid(Long memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.shopid
     *
     * @return the value of tb_flow.shopid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Long getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.shopid
     *
     * @param shopid the value for tb_flow.shopid
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setShopid(Long shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.created
     *
     * @return the value of tb_flow.created
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.created
     *
     * @param created the value for tb_flow.created
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}