package com.jesper.model;

import java.util.Date;

public class Member extends BaseObject{
    private Long id;
    private String pname;
    private String pwd;
    private String realname;
    private String phone;
    private String pos;
    private String pcode;
    private String headpic;
    private Byte state;
    private Date created;
    private Date updated;
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.id
     *
     * @param id the value for tb_member.id
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.pname
     *
     * @return the value of tb_member.pname
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.pname
     *
     * @param pname the value for tb_member.pname
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.pwd
     *
     * @return the value of tb_member.pwd
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.pwd
     *
     * @param pwd the value for tb_member.pwd
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.realname
     *
     * @return the value of tb_member.realname
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.realname
     *
     * @param realname the value for tb_member.realname
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.phone
     *
     * @return the value of tb_member.phone
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.phone
     *
     * @param phone the value for tb_member.phone
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.pos
     *
     * @return the value of tb_member.pos
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.pos
     *
     * @param pos the value for tb_member.pos
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setPos(String pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.pcode
     *
     * @return the value of tb_member.pcode
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.pcode
     *
     * @param pcode the value for tb_member.pcode
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setPcode(String pcode) {
        this.pcode = pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.headpic
     *
     * @return the value of tb_member.headpic
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getHeadpic() {
        return headpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.headpic
     *
     * @param headpic the value for tb_member.headpic
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setHeadpic(String headpic) {
        this.headpic = headpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.state
     *
     * @return the value of tb_member.state
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.state
     *
     * @param state the value for tb_member.state
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.created
     *
     * @return the value of tb_member.created
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.created
     *
     * @param created the value for tb_member.created
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.updated
     *
     * @return the value of tb_member.updated
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.updated
     *
     * @param updated the value for tb_member.updated
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}