package com.jesper.model;

import java.util.Date;

import lombok.Data;

@Data
public class Quancat extends BaseObject{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.id
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.qname
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private String qname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.qdesc
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private String qdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.image
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.qprice
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private String qprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.qtimes
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private Integer qtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.qcoup
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private Float qcoup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.lastnum
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private Integer lastnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.holdnum
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private Integer holdnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.validshops
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private String validshops;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.status
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.created
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quancat.updated
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    private Date updated;

    
}