package com.jesper.model;

import java.util.Date;

public class Shop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.id
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.sname
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.scode
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private String scode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.slxr
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private String slxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.sphone
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private String sphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shopcomment
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private String shopcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shopaddr
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private String shopaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.state
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.created
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.updated
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.id
     *
     * @return the value of tb_shop.id
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.id
     *
     * @param id the value for tb_shop.id
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.sname
     *
     * @return the value of tb_shop.sname
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.sname
     *
     * @param sname the value for tb_shop.sname
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.scode
     *
     * @return the value of tb_shop.scode
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.scode
     *
     * @param scode the value for tb_shop.scode
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setScode(String scode) {
        this.scode = scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.slxr
     *
     * @return the value of tb_shop.slxr
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getSlxr() {
        return slxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.slxr
     *
     * @param slxr the value for tb_shop.slxr
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setSlxr(String slxr) {
        this.slxr = slxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.sphone
     *
     * @return the value of tb_shop.sphone
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getSphone() {
        return sphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.sphone
     *
     * @param sphone the value for tb_shop.sphone
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setSphone(String sphone) {
        this.sphone = sphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.shopcomment
     *
     * @return the value of tb_shop.shopcomment
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getShopcomment() {
        return shopcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.shopcomment
     *
     * @param shopcomment the value for tb_shop.shopcomment
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setShopcomment(String shopcomment) {
        this.shopcomment = shopcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.shopaddr
     *
     * @return the value of tb_shop.shopaddr
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public String getShopaddr() {
        return shopaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.shopaddr
     *
     * @param shopaddr the value for tb_shop.shopaddr
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setShopaddr(String shopaddr) {
        this.shopaddr = shopaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.state
     *
     * @return the value of tb_shop.state
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.state
     *
     * @param state the value for tb_shop.state
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.created
     *
     * @return the value of tb_shop.created
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.created
     *
     * @param created the value for tb_shop.created
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.updated
     *
     * @return the value of tb_shop.updated
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.updated
     *
     * @param updated the value for tb_shop.updated
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}