package com.jesper.model;

import java.util.Date;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.id
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.title
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.sell_point
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    private String sellPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.price
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.num
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.barcode
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.image
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.cid
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.status
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.created
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.updated
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.id
     *
     * @return the value of tb_test.id
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.id
     *
     * @param id the value for tb_test.id
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.title
     *
     * @return the value of tb_test.title
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.title
     *
     * @param title the value for tb_test.title
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.sell_point
     *
     * @return the value of tb_test.sell_point
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public String getSellPoint() {
        return sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.sell_point
     *
     * @param sellPoint the value for tb_test.sell_point
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public void setSellPoint(String sellPoint) {
        this.sellPoint = sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.price
     *
     * @return the value of tb_test.price
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.price
     *
     * @param price the value for tb_test.price
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.num
     *
     * @return the value of tb_test.num
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.num
     *
     * @param num the value for tb_test.num
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.barcode
     *
     * @return the value of tb_test.barcode
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.barcode
     *
     * @param barcode the value for tb_test.barcode
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.image
     *
     * @return the value of tb_test.image
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.image
     *
     * @param image the value for tb_test.image
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.cid
     *
     * @return the value of tb_test.cid
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.cid
     *
     * @param cid the value for tb_test.cid
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.status
     *
     * @return the value of tb_test.status
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.status
     *
     * @param status the value for tb_test.status
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.created
     *
     * @return the value of tb_test.created
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.created
     *
     * @param created the value for tb_test.created
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.updated
     *
     * @return the value of tb_test.updated
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.updated
     *
     * @param updated the value for tb_test.updated
     *
     * @mbggenerated Tue Mar 23 09:14:48 CST 2021
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}