package com.jesper.model;

public class Ver {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ver.id
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ver.versioncode
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    private String versioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ver.versionnum
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    private Integer versionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ver.isforce
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    private Short isforce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ver.updateurl
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    private String updateurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ver.size
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ver.updatetips
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    private String updatetips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ver.wgt_flag
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    private Integer wgtFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ver.wgt_url
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    private String wgtUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ver.id
     *
     * @return the value of tb_ver.id
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ver.id
     *
     * @param id the value for tb_ver.id
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ver.versioncode
     *
     * @return the value of tb_ver.versioncode
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public String getVersioncode() {
        return versioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ver.versioncode
     *
     * @param versioncode the value for tb_ver.versioncode
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public void setVersioncode(String versioncode) {
        this.versioncode = versioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ver.versionnum
     *
     * @return the value of tb_ver.versionnum
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public Integer getVersionnum() {
        return versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ver.versionnum
     *
     * @param versionnum the value for tb_ver.versionnum
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public void setVersionnum(Integer versionnum) {
        this.versionnum = versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ver.isforce
     *
     * @return the value of tb_ver.isforce
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public Short getIsforce() {
        return isforce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ver.isforce
     *
     * @param isforce the value for tb_ver.isforce
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public void setIsforce(Short isforce) {
        this.isforce = isforce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ver.updateurl
     *
     * @return the value of tb_ver.updateurl
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public String getUpdateurl() {
        return updateurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ver.updateurl
     *
     * @param updateurl the value for tb_ver.updateurl
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public void setUpdateurl(String updateurl) {
        this.updateurl = updateurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ver.size
     *
     * @return the value of tb_ver.size
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ver.size
     *
     * @param size the value for tb_ver.size
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ver.updatetips
     *
     * @return the value of tb_ver.updatetips
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public String getUpdatetips() {
        return updatetips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ver.updatetips
     *
     * @param updatetips the value for tb_ver.updatetips
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public void setUpdatetips(String updatetips) {
        this.updatetips = updatetips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ver.wgt_flag
     *
     * @return the value of tb_ver.wgt_flag
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public Integer getWgtFlag() {
        return wgtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ver.wgt_flag
     *
     * @param wgtFlag the value for tb_ver.wgt_flag
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public void setWgtFlag(Integer wgtFlag) {
        this.wgtFlag = wgtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ver.wgt_url
     *
     * @return the value of tb_ver.wgt_url
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public String getWgtUrl() {
        return wgtUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ver.wgt_url
     *
     * @param wgtUrl the value for tb_ver.wgt_url
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    public void setWgtUrl(String wgtUrl) {
        this.wgtUrl = wgtUrl;
    }
}