package com.jesper.mapper;

import com.jesper.model.Flow;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface FlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    int insert(Flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    Flow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    List<Flow> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    int updateByPrimaryKey(Flow record);
}