package com.jesper.mapper;

import com.jesper.model.Member;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    Member selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    List<Member> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Mar 26 08:52:34 CST 2021
     */
    int updateByPrimaryKey(Member record);

	Member selectByNameAndPwd(Member member);
}