package com.jesper.mapper;

import com.jesper.model.Quan;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface QuanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quan
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quan
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    int insert(Quan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quan
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    Quan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quan
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    List<Quan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quan
     *
     * @mbggenerated Tue Mar 23 16:40:00 CST 2021
     */
    int updateByPrimaryKey(Quan record);

	List<Quan> list(Quan quan);

	int count(Quan quan);
}