package com.jesper.mapper;

import com.jesper.model.Test;
import java.util.List;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Tue Mar 23 09:14:49 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Tue Mar 23 09:14:49 CST 2021
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Tue Mar 23 09:14:49 CST 2021
     */
    Test selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Tue Mar 23 09:14:49 CST 2021
     */
    List<Test> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Tue Mar 23 09:14:49 CST 2021
     */
    int updateByPrimaryKey(Test record);
}