package com.jesper.mapper;

import com.jesper.model.Ver;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface VerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ver
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ver
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    int insert(Ver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ver
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    Ver selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ver
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    List<Ver> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ver
     *
     * @mbggenerated Fri Apr 09 16:10:19 CST 2021
     */
    int updateByPrimaryKey(Ver record);
    
    List<Ver> selectLast(Integer code);
}